%YAML:1.0

# akaze61 parameters

# Feature Extractor
FeatureExtractor.nOctaves: 8
FeatureExtractor.scaleFactor: 1.1892 # 2^0.25
FeatureExtractor.detectTh: 0.0005
FeatureExtractor.maxNumFeatures: 1000

# Feature Matcher
FeatureMatcher.TH_LOW: 86
FeatureMatcher.descDistTh_high_reloc: 185
FeatureMatcher.descDistTh_low_reloc: 113
