%YAML:1.0

# sift128 parameters

# Feature Extractor
FeatureExtractor.nOctaves: 4
FeatureExtractor.scaleFactor: 2.0
FeatureExtractor.detectTh: 0.0066
FeatureExtractor.maxNumFeatures: 1000

# Feature Matcher
FeatureMatcher.TH_LOW: 0.48
FeatureMatcher.descDistTh_high_reloc: 1.0
FeatureMatcher.descDistTh_low_reloc: 0.62
