%YAML:1.0

# surf64 parameters

# Feature Extractor 
FeatureExtractor.nOctaves: 8
FeatureExtractor.scaleFactor: 1.2
FeatureExtractor.detectTh: 100.0
FeatureExtractor.maxNumFeatures: 1000

# Feature Matcher 
FeatureMatcher.TH_HIGH: 0.04
FeatureMatcher.TH_LOW: 0.04
FeatureMatcher.descDistTh_high_reloc: 0.04
FeatureMatcher.descDistTh_low_reloc: 0.04
