#!/usr/bin/env python3
"""Generate docs/reference/settings.md: every settings key the code reads, where, and its dev-YAML value.

Sources of truth, in this order:
- the code: `read_if_present("Block.Key", field)` calls and `fSettings["Block.Key"]` reads under
  `src/` and `include/` give the key and the file:line that reads it;
- `vslamlab_allfeature-dev_settings.yaml` gives the value shipped with the dev baseline and the
  trailing `# comment` on the same line (the human description);
- the per-file reference pages (`docs/reference/<File>.md`) give the page a key links to, by the
  file that reads it.

Keys present in the YAML but read nowhere, and keys read but absent from the YAML, are listed at
the end so the two stay in sync. Usage:

    python docs/tools/settings_keys.py            # rewrite docs/reference/settings.md
    python docs/tools/settings_keys.py --check    # exit 1 if the page would change
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
REPO_URL = "https://github.com/alejandrofontan/AllFeature-VSLAM/blob/main/"
YAML = REPO_ROOT / "vslamlab_allfeature-dev_settings.yaml"
OUT = REPO_ROOT / "docs" / "reference" / "settings.md"

# every idiom the code uses to read a key: read_if_present("K", …) / readIfPresent("K", …) lambdas,
# fSettings["K"] / settingsNode["K"] / settings["K"] indexing (cv::FileStorage or yaml-cpp), and the
# FramePacer-style `kSettingsKey = "K"` constant
READ_RE = re.compile(
    r'\b\w*[Rr]ead\w*\s*\(\s*"(?P<key>[A-Za-z][\w.]*)"'
    r'|\w+\s*\[\s*"(?P<key2>[A-Za-z][\w.]*)"\s*\]'
    r'|SettingsKey\s*=\s*"(?P<key3>[A-Za-z][\w.]*)"'
)
YAML_RE = re.compile(r'^(?P<key>[A-Za-z][\w.]*)\s*:\s*(?P<val>[^#]*?)\s*(?:#\s*(?P<comment>.*))?$')
# top-level (block-less) keys of the settings YAML, so `settings["features"]`-style reads count but
# `map["orb32"]`-style indexing of other containers does not
TOP_LEVEL_KEYS = {"cam_mono", "features", "vpr", "feature_vpr", "megaloc_onnx", "megaloc_precision",
                  "segmentation", "segmentation_onnx", "debug", "max_frame_wait"}

# reference page per source-file stem (a file family shares one page)
PAGE_OF = {
    "Tracking": "Tracking", "Tracking_aux": "Tracking",
    "LocalMapping": "LocalMapping", "LocalMapping_aux": "LocalMapping",
    "LoopClosing": "LoopClosing", "LoopClosing_aux": "LoopClosing",
    "System": "System", "Viewer": "Viewer", "Optimizer": "Optimizer",
    "PlaceCellSettings": "System", "SegmentationSettings": "System",
    "PlaceRecognitionMegaLoc": "PlaceRecognition", "PlaceRecognition": "PlaceRecognition",
    "KeyframeInformation": "KeyframeInformation",
}


def code_reads() -> dict[str, list[tuple[str, int]]]:
    reads: dict[str, list[tuple[str, int]]] = {}
    for path in sorted((*REPO_ROOT.glob("src/*.c*"), *REPO_ROOT.glob("include/*.h*"))):
        for i, line in enumerate(path.read_text(errors="replace").splitlines(), 1):
            if line.lstrip().startswith("//"):
                continue
            for m in READ_RE.finditer(line):
                key = m["key"] or m["key2"] or m["key3"]
                # indexing idiom: only settings-shaped keys (Block.Key) or the known top-level ones
                if m["key2"] and "." not in key and key not in TOP_LEVEL_KEYS:
                    continue
                reads.setdefault(key, []).append((str(path.relative_to(REPO_ROOT)), i))
    return reads


def yaml_entries() -> dict[str, tuple[str, str]]:
    out: dict[str, tuple[str, str]] = {}
    for line in YAML.read_text().splitlines():
        m = YAML_RE.match(line)
        if m and m["key"] != "%YAML":
            out[m["key"]] = (m["val"].strip(), (m["comment"] or "").strip())
    return out


def page_link(src: str) -> str:
    stem = pathlib.Path(src).stem
    page = PAGE_OF.get(stem)
    exists = page and (REPO_ROOT / "docs" / "reference" / f"{page}.md").exists()
    return f"[{page}]({page}.md)" if exists else (page or "—")


def render() -> str:
    reads, yaml = code_reads(), yaml_entries()
    keys = sorted(set(reads) | set(yaml), key=lambda k: (k.split(".")[0] if "." in k else "", k))
    lines = [
        "# Settings reference",
        "",
        "Every key read from the settings YAML (`vslamlab_allfeature-dev_settings.yaml`), the value the dev",
        "baseline ships, where the code reads it and the reference page of that file. Generated by",
        "`docs/tools/settings_keys.py` from the code and the YAML; edit those, not this page. A missing key",
        "keeps the compiled-in default (each `LoadParameters` reads only the keys present).",
        "",
    ]
    block = None
    for k in keys:
        b = k.split(".")[0] if "." in k else "(top level)"
        if b != block:
            block = b
            lines += ["", f"## {block}", "", "| Key | Dev YAML value | Read in | Page | Description (YAML comment) |", "|---|---|---|---|---|"]
        val, comment = yaml.get(k, ("*(not in the YAML)*", ""))
        # the title is the resolver's search pattern (a Markdown title cannot contain quotes, so the bare key)
        where = ", ".join(f"[{pathlib.Path(s).name}#L{ln}]({REPO_URL}{s}#L{ln} \"{k}\")" for s, ln in reads.get(k, [])) or "*(read nowhere)*"
        pages = ", ".join(sorted({page_link(s) for s, _ in reads.get(k, [])})) or "—"
        lines.append(f"| `{k}` | `{val}` | {where} | {pages} | {comment} |")
    unread = [k for k in yaml if k not in reads]
    unlisted = [k for k in reads if k not in yaml]
    lines += ["", "## Consistency", ""]
    lines.append(f"- In the YAML but read nowhere: {', '.join(f'`{k}`' for k in unread) if unread else 'none'}.")
    lines.append(f"- Read by the code but absent from the YAML: {', '.join(f'`{k}`' for k in unlisted) if unlisted else 'none'}.")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    new = render()
    old = OUT.read_text() if OUT.exists() else ""
    if args.check:
        if new != old:
            print(f"{OUT.relative_to(REPO_ROOT)} is out of date; run docs/tools/settings_keys.py")
            return 1
        print("settings.md up to date")
        return 0
    OUT.write_text(new)
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({new.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
