#ifndef ALLFEATURE_VSLAM_DEFINITIONS_H
#define ALLFEATURE_VSLAM_DEFINITIONS_H

#define ALLFEATURE_EVALUATION 50
#define ALLFEATURE_REAL_TIME
#define ALLFEATURE_MAX_KEYFRAMES 10
#define ALLFEATURE_KEYFRAMES 10

//#define PROFILING_EXHAUSTIVE


#endif //ALLFEATURE_VSLAM_DEFINITIONS_H
